### ISSUE TITLE
svscan should propagate SIGTERM to child supervise processes (e.g. for docker)

### ISSUE THREAD

**Issue by timbunce** [bruceg/daemontools-encore#30]
We're migrating our systems to docker. We use daemontools-encore and currently have docker run svscan as the main process. That appears to work well until the container is stopped.

When a container is stopped docker sends the main process a SIGTERM then waits for 30 second for all the processes in the container to exit. Any processes still running after 30 seconds are sent a SIGKILL.

When using svscan as the main process the svscan gets the SIGTERM but doesn't propagate it to child supervise processes. So they're unaware of the desire to stop the system until they get terminated violently in bulk with a SIGKILL.

I'm likely to switch to using [s6](http://www.skarnet.org/software/s6/why.html) as it [handles this case well](http://blog.tutum.co/2014/12/02/docker-and-s6-my-new-favorite-process-supervisor/).

**Comment by rehsack** [comment]
Hi Tim,

since we're using daemontools-encore as well (and identified the same problem with not so burning priority), developing a patch would help us both. Can you try out a patch when I provide you one, or do you need kind-of release? (depends on you processes, so I ask before ...)

@bruceg - how's you maintaining policy? Seems there're some unhandled PR's ;)

**Comment by bruceg** [comment]
Fixed by pull #52
